### ISSUE TITLE
Error message not shown on unsuccessful login

### ISSUE THREAD

**Issue by evadecker** [namesakefyi/namesake#167]
**Describe the bug**
Currently if a user fails to log in, the form is cleared and no message is displayed.

**To Reproduce**
1. Log in with incorrect credentials or nonexistent account
2. No message is displayed

**Expected behavior**
An error displays letting the user know the account doesn't exist or the password is wrong.

**Comment by evadecker** [comment]
Hi @Gulin7! If you want to work on this that would be awesome. You should be able to use the existing [Banner](https://github.com/namesakefyi/namesake/blob/main/src/components/Banner/Banner.tsx) component here matching similar styles to [here](https://github.com/namesakefyi/namesake/blob/eebd9b6642f63f6045a445c194dbe0e8a48d2558/src/routes/_unauthenticated/signin.tsx#L197).

Make sure to check out the [contribution guidelines](https://github.com/namesakefyi/namesake/blob/main/CONTRIBUTING.md).

**Comment by evadecker** [comment]
@Gulin7 I came across this example of handling errors during auth (from [this message on Discord](https://discord.com/channels/1019350475847499849/1278048435513069660/1308458883521708073)), might be worth looking at as inspiration: https://github.com/get-convex/convex-auth/commit/c95f02700207a7679189ad3fbb1765512e085615

**Comment by Gulin7** [comment]
@evadecker I'm currently busy, but I'll get at it starting Wednesday-Thursday

**Comment by ansen01-svg** [comment]
@evadecker It seems that there is no email and password validator. If that is the intended behaviour, than I can display custom error messages on singin and register failure as it is implemented here:  [get-convex/convex-auth@](https://github.com/get-convex/convex-auth/commit/c95f02700207a7679189ad3fbb1765512e085615)

**Comment by evadecker** [comment]
> @evadecker It seems that there is no email and password validator. If that is the intended behaviour, then I can display custom error messages on singin and register failure as it is implemented here:  [get-convex/convex-auth@](https://github.com/get-convex/convex-auth/commit/c95f02700207a7679189ad3fbb1765512e085615)

There are definitely improvements we could make to the login flow! Right now the implementation is very barebones. If you see opportunities for additional validation logic feel free to suggest how to add it!
