### ISSUE TITLE
Write unit tests for settings page and components

### ISSUE THREAD

**Issue by evadecker** [namesakefyi/namesake#235]
Write unit tests for

- `DeleteAccountSetting`
- `EditBirthplaceSetting`
- `EditMinorSetting`
- `EditNameSetting`
- `EditResidenceSetting`
- `EditThemeSetting`

If tests uncover any issues with the components, make improvements, paying attention to failure states and loading states.

**Comment by belhajManel** [comment]
For unit tests related to `DeleteAccountSetting` `EditNameSetting`  `EditResidenceSetting` `EditBirthplaceSetting`  we'll need to write tests related to the modals only , is that correct?

**Comment by evadecker** [comment]
> For unit tests related to `DeleteAccountSetting` `EditNameSetting`  `EditResidenceSetting` `EditBirthplaceSetting`  we'll need to write tests related to the modals only , is that correct?

We'd also need to test the button contents, but it's mostly just the modals!
