### ISSUE TITLE
Dialogs must all contain `<Heading slot="title">`

### ISSUE THREAD

**Issue by evadecker** [namesakefyi/namesake#236]
**Describe the bug**
There are repeated accessibility warnings during unit tests about Dialogs needing a Heading. See https://github.com/namesakefyi/namesake/actions/runs/12063047643/job/33637643950#step:6:1

**To Reproduce**
1. Run Vitest
2. Warnings will display

**Expected behavior**
All Dialogs have the appropriate headings and no warnings are displayed.

**Comment by gingerchew** [comment]
I can take a crack at this

**Comment by gingerchew** [comment]
I wonder if the `<EditQuestTimeRequired />` component is giving a false positive for it's warning. Inside that component is a `<Dialog />` that contains a `<ModalHeader />` which then contains the required `<Heading slot="title" />` component.

Is that being missed by the test or should the `<Heading slot="title" />` be a direct child of the `<Dialog />` component?

**Comment by evadecker** [comment]
Thanks for digging in here! You had the same thought as I did. It might be worth digging into React Aria docs to better understand how [Header](https://react-spectrum.adobe.com/react-spectrum/Header.html#content) and [Dialog](https://react-spectrum.adobe.com/react-aria/Dialog.html#dialog) are meant to be composed together.

**Comment by gingerchew** [comment]
Yes chef! 👩‍🍳

**Comment by gingerchew** [comment]
[This test in RAC](https://github.com/adobe/react-spectrum/blob/main/packages/react-aria-components/test/Dialog.test.js#L237-L251) makes me think we could get away with using the `aria-label` attribute but I'll test when not a holiday 😁

**Comment by evadecker** [comment]
@gingerchew I figured out what the issue was! `Dialog` is inherited by `Popover`, `Select`, and `Menu`, so all the errors were from those components being rendered/re-rendered without a title. #285 fixes it.
