### ISSUE TITLE
Improve 404 page display

### ISSUE THREAD

**Issue by evadecker** [namesakefyi/namesake#248]
It would be helpful to display navigation on the 404 page. Design and implement an improvement.

![CleanShot 2024-12-01 at 22 14 15@2x](https://github.com/user-attachments/assets/29dc5880-ff14-4d6f-a993-99d697ba365d)

**Comment by ansen01-svg** [comment]
Like adding a simple "go back to home page" link?

**Comment by evadecker** [comment]
@ansen01-svg Thanks so much for being the first contributor to the Namesake repo! ❤️

**Comment by ansen01-svg** [comment]
I am glad to contribute.
