### ISSUE TITLE
Display an error message on sign in if the email does not belong to a registered user

### ISSUE THREAD

**Issue by evadecker** [namesakefyi/namesake#296]
If a user attempts to sign in using an email that doesn't exist in the database, display an error banner.

The banner should say:

> There isn't an account for this email. Would you like to [register a new account]?

"register a new account" should link to the registration tab.

**Comment by nakul-py** [comment]
Hi @evadecker 
I came across this issue and would like to work on resolving it. Could you please assign it to me?

**Comment by evadecker** [comment]
Hey @nakul-py! We don't assign issues, but feel free to put up a PR for this and we will review it!
